// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tswongjlayttrzgzimrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzd29uZ2psYXl0dHJ6Z3ppbXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NzE5MjgsImV4cCI6MjA2MjE0NzkyOH0.I2YKpB65lqkgZsd3OzLJX2wI40XFIvR9qLuhiXRN4qs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);